<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIHFU2U" failures="2" tests="6" name="Test(failed)" time="68.225" errors="0" timestamp="2025-01-30T01:20:24 EST">
  <testcase classname="codenbox.testCases.LoginTest" name="verify_login" time="11.31">
    <skipped/>
  </testcase> <!-- verify_login -->
  <testcase classname="codenbox.testCases.LoginTest" name="verify_login" time="11.56">
    <skipped/>
  </testcase> <!-- verify_login -->
  <testcase classname="codenbox.testCases.LoginTest" name="verify_login" time="11.088">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at codenbox.testCases.LoginTest.verify_login(LoginTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
  <testcase classname="codenbox.testCases.RegistrationTest" name="verify_registration" time="2.282">
    <skipped/>
  </testcase> <!-- verify_registration -->
  <testcase classname="codenbox.testCases.RegistrationTest" name="verify_registration" time="2.056">
    <skipped/>
  </testcase> <!-- verify_registration -->
  <testcase classname="codenbox.testCases.RegistrationTest" name="verify_registration" time="2.049">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at codenbox.testCases.RegistrationTest.verify_registration(RegistrationTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_registration -->
</testsuite> <!-- Test(failed) -->
